import asyncio
import json
import sys
from types import ModuleType

import pytest

from pr_review_runner.description_runner import _generate, _pull_url, _write_summary_output


def test_pull_url_supports_pull_and_issue_comment_events() -> None:
    pull_event = {"pull_request": {"url": "https://api.github.test/pulls/7"}}
    comment_event = {"issue": {"pull_request": {"url": "https://api.github.test/pulls/8"}}}

    assert _pull_url(pull_event).endswith("/7")
    assert _pull_url(comment_event).endswith("/8")


def test_pull_url_rejects_non_pull_request_events() -> None:
    with pytest.raises(ValueError, match="pull-request URL"):
        _pull_url({"issue": {"number": 7}})


def test_write_summary_output_uses_structured_json(tmp_path) -> None:
    output = tmp_path / "output"

    _write_summary_output(output, "中文摘要")

    key, value = output.read_text(encoding="utf-8").strip().split("=", 1)
    assert key == "description"
    assert json.loads(value) == {"summary": "中文摘要"}


@pytest.mark.parametrize(
    "artifact",
    [
        "### 🤖 Generated by PR Agent at abcdef\n\nFirst point.\nSecond point.",
        "First point.\nSecond point.",
        "Replaces the `pr_agent:summary` placeholder after generation.",
    ],
)
def test_generate_preserves_upstream_artifact_and_disables_publication(monkeypatch, artifact) -> None:
    calls: list[tuple[str, object]] = []

    class FakeSettings:
        data: dict | None = None

        def set(self, key: str, value: object) -> None:
            calls.append((key, value))

    settings = FakeSettings()

    class FakeDescription:
        def __init__(self, pr_url: str) -> None:
            assert pr_url == "https://api.github.test/pulls/7"
            self.user_description = "Contributor body."

        async def run(self) -> None:
            assert self.user_description == "pr_agent:summary"
            settings.data = {"artifact": artifact}

    config_loader = ModuleType("pr_agent.config_loader")
    config_loader.get_settings = lambda: settings
    provider_utils = ModuleType("pr_agent.git_providers.utils")
    provider_utils.apply_repo_settings = lambda url: calls.append(("repo", url))
    description_module = ModuleType("pr_agent.tools.pr_description")
    description_module.PRDescription = FakeDescription
    monkeypatch.setitem(sys.modules, "pr_agent", ModuleType("pr_agent"))
    monkeypatch.setitem(sys.modules, "pr_agent.config_loader", config_loader)
    monkeypatch.setitem(sys.modules, "pr_agent.git_providers", ModuleType("pr_agent.git_providers"))
    monkeypatch.setitem(sys.modules, "pr_agent.git_providers.utils", provider_utils)
    monkeypatch.setitem(sys.modules, "pr_agent.tools", ModuleType("pr_agent.tools"))
    monkeypatch.setitem(sys.modules, "pr_agent.tools.pr_description", description_module)
    monkeypatch.setenv("GITHUB_TOKEN", "github-token")

    summary = asyncio.run(_generate("https://api.github.test/pulls/7"))

    assert summary == artifact
    assert calls == [
        ("GITHUB.USER_TOKEN", "github-token"),
        ("GITHUB.DEPLOYMENT_TYPE", "user"),
        ("repo", "https://api.github.test/pulls/7"),
        ("CONFIG.PUBLISH_OUTPUT", False),
    ]


def test_generate_rejects_unreplaced_private_placeholder(monkeypatch) -> None:
    class FakeSettings:
        data: dict | None = None

        def set(self, key: str, value: object) -> None:
            pass

    settings = FakeSettings()

    class FakeDescription:
        def __init__(self, pr_url: str) -> None:
            self.user_description = "Contributor body."

        async def run(self) -> None:
            settings.data = {"artifact": "pr_agent:summary"}

    config_loader = ModuleType("pr_agent.config_loader")
    config_loader.get_settings = lambda: settings
    provider_utils = ModuleType("pr_agent.git_providers.utils")
    provider_utils.apply_repo_settings = lambda url: None
    description_module = ModuleType("pr_agent.tools.pr_description")
    description_module.PRDescription = FakeDescription
    monkeypatch.setitem(sys.modules, "pr_agent", ModuleType("pr_agent"))
    monkeypatch.setitem(sys.modules, "pr_agent.config_loader", config_loader)
    monkeypatch.setitem(sys.modules, "pr_agent.git_providers", ModuleType("pr_agent.git_providers"))
    monkeypatch.setitem(sys.modules, "pr_agent.git_providers.utils", provider_utils)
    monkeypatch.setitem(sys.modules, "pr_agent.tools", ModuleType("pr_agent.tools"))
    monkeypatch.setitem(sys.modules, "pr_agent.tools.pr_description", description_module)
    monkeypatch.setenv("GITHUB_TOKEN", "github-token")

    with pytest.raises(RuntimeError, match="produced no Summary"):
        asyncio.run(_generate("https://api.github.test/pulls/7"))
